sonar.projectKey=National-Node-Net_ndt-overwatch
sonar.organization=national-node-net
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.test.js
sonar.coverage.exclusions=**/*.test.js
sonar.featureflag.cloud-security-enable-generic-yaml-and-json-analyzer=true
